In [3]:
import torch 

In [19]:
# creating empty tensor in one dimension means SCALER
x = torch.empty(1)
print(x)

tensor([-1.0354e-37])


In [20]:
# if we want a three dimensional tensor
y = torch.empty(3)
print(y)

tensor([ 0.0000e+00,  2.0000e+00, -1.5895e-37])


In [21]:
# if we want to make a two dimensional matrix then:--\
matrix = torch.empty(2,3)
print(matrix)

tensor([[8.4078e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [22]:
matrix = torch.empty(2,2,2)
print(matrix)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [23]:
matrix = torch.empty(2,2,2,2)
print(matrix)



tensor([[[[0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 2.0000e+00],
          [0.0000e+00, 2.0000e+00]]],


        [[[7.0065e-45, 0.0000e+00],
          [7.4014e-33, 4.5918e-40]],

         [[7.3978e-33, 1.4013e-45],
          [0.0000e+00, 0.0000e+00]]]])


In [25]:
# we can create tensor with random values  (here creating 2*2 tensor)
x = torch.rand(2,2)
print(x)

tensor([[0.8127, 0.4211],
        [0.9304, 0.0384]])


In [26]:
# in DEEP LEARNIGN we sometimes want to initialize or weight matrix with 1 or 0 value in so many architecture such as in Hopfield network

x = torch.zeros(3,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [31]:
x = torch.ones(3,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [32]:
# we can also give specific data type (default is float32). we can make it to integer also 
x = torch.ones(2,2, dtype=torch.int)
print(x.dtype)

torch.int32


In [33]:
x = torch.ones(2,2, dtype=torch.float16)
print(x.dtype)

torch.float16


In [34]:
print(x.size())

torch.Size([2, 2])


In [35]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [36]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)

tensor([[0.2438, 0.9080],
        [0.5865, 0.0632]])
tensor([[0.6531, 0.3227],
        [0.3157, 0.0276]])


In [37]:
z = x + y
print(z)

tensor([[0.8968, 1.2307],
        [0.9022, 0.0908]])


In [39]:
# we can add these two tensor in this way also:- 
z = torch.add(x,y)
print(z)

tensor([[0.8968, 1.2307],
        [0.9022, 0.0908]])


In [40]:
# if we want to modify one of the tensor then:- adding x tensor into y

y.add_(x)



tensor([[0.8968, 1.2307],
        [0.9022, 0.0908]])

In [41]:
z = x - y
print(z)

tensor([[-0.6531, -0.3227],
        [-0.3157, -0.0276]])


In [42]:
z = torch.sub(x,y)
print(z)

tensor([[-0.6531, -0.3227],
        [-0.3157, -0.0276]])


In [43]:
# if we want to multipy two tensor
z = torch.mul(x,y)
print(z)

tensor([[0.2186, 1.1175],
        [0.5292, 0.0057]])


In [44]:
# if we want to devide the two tensors
z = torch.div(x,y)
print(z)

tensor([[0.2718, 0.7378],
        [0.6501, 0.6964]])


In [45]:
# slicing of tensor 

x = torch.rand(5,3)
print(x)

tensor([[0.2469, 0.7741, 0.8457],
        [0.1288, 0.0746, 0.0278],
        [0.4550, 0.5083, 0.5921],
        [0.3437, 0.1594, 0.7729],
        [0.1644, 0.5953, 0.3693]])


In [48]:
# if the matrix size is large and we want to see any specific row or column
# all rows but first column
print(x[:,0])


tensor([0.2469, 0.1288, 0.4550, 0.3437, 0.1644])


In [50]:
print(x[0,:])
# all columns but first row

tensor([0.2469, 0.7741, 0.8457])


In [51]:
# reshaping a tensor
x = torch.rand(4,4)
print(x)

tensor([[0.8880, 0.9922, 0.7955, 0.8513],
        [0.4273, 0.5720, 0.2855, 0.3959],
        [0.8551, 0.5397, 0.3048, 0.2371],
        [0.4531, 0.2253, 0.9201, 0.1743]])


In [52]:
y = x.view(16)
# number of elements is 16 i-e 4*4=16

In [54]:
# if we doont want to put value in dimension, pytorch will automatically detect it 

y = x.view(-1,8)
print(y)

tensor([[0.8880, 0.9922, 0.7955, 0.8513, 0.4273, 0.5720, 0.2855, 0.3959],
        [0.8551, 0.5397, 0.3048, 0.2371, 0.4531, 0.2253, 0.9201, 0.1743]])


In [55]:
print(y.size())

torch.Size([2, 8])


In [56]:
# CONVERTIING A NUMPY TENSOR TO A PYTORCH TENSOR
import numpy as np

In [58]:
# creating a tensor 
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [59]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [60]:
type(b)

numpy.ndarray

In [62]:
# NOTE: if we are working on CPU then these both will share the same memory, so use inplace
a.add_(1)
print(a)
print(b)
# we can see here is that addition is done in both  

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [63]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [64]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [65]:
a+=1
print(a)
print(b)

# here its updated too

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [69]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+y
print(z)
# this code can be used to locate pytorch tensor on GPU and the numpy tensor will stay in CPU.
# thus the updation done in pytorch wont reflect in numy

tensor([[0.2718, 0.7378],
        [0.6501, 0.6964]])


In [73]:
z = z.to("cpu")
# to shift back to CPU
print(z)

tensor([[0.2718, 0.7378],
        [0.6501, 0.6964]])


In [74]:
# later in our optimization steps if we want to calculate gradiants then we can mension it easily in the valriable x.

x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
